name: Ultra Simple Test
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "🤖 Hello from GitHub Actions!"
          echo "📱 Testing KMP build..."
          ./gradlew :shared:assembleIosX64
          echo "🎉 If you see this - IT WORKS!"